version: '3' # composeファイルのバーション指定
services:
    picoctf: # service名
        build: . # ビルドに使用するDockerfileがあるディレクトリ指定
        tty: true # コンテナの起動永続化
        volumes:
            - .:/picoCTF # マウントディレクトリ指定